### ISSUE TITLE
site jsou vpici??

### ISSUE THREAD

**Issue by Pzdrs** [Bahamut731lp/PST#1]
ten clovek se neozval ze proc se kurva nedostavil?? nemate nejaky info kdy budem psat ten spiceneckej test? on neodpovi na email proste tak nevim to je konecna bro

**Comment by Bahamut731lp** [comment]
Taky jsem mu psal mail a nedostal jsem odpověď. V nejhorším případě ho bude muset někdo snipenout v kanclu

**Comment by Bahamut731lp** [comment]
@Pzdrs edit: Dostal jsem pár minut zpátky zápočet

**Comment by Pzdrs** [comment]
Dopici co ted
